[package]
name = "wurth-wsen-hids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "wurth_wsen_hids"

[dependencies]
embedded-hal = "0.2.7"
fugit = "0.3.6"
heapless = "0.7.16"
